
theme: jekyll-theme-minimal
title: Shark Education's homepage
description: Bookmark this to keep an eye on my project updates!
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #
title: [Voyages Shark Education]
description: [Retrouvez ici tous les voyages Shark Education prévus pour l'année 2023. Téléchargez les PDF et demandez vos devis !]
